### ISSUE TITLE
[Create] - UI

### ISSUE THREAD

**Issue by leonardoriviere** [leonardoriviere/errai-tutorial#8]
Ticket class must adapt to the service, to allow interaction with the database. (Named Queries)
    ◦ Create named query.
Methods that are in the client side must create tables and use the information that the service returns.
    ◦ Create method to build the table.
    ▪ Create method to save.
    ▪ Create method to update.
    ▪ Create table builder method.

ET: 6/7 hours.

**Comment by cristianmiranda** [comment]
This issue was moved to freelance-factory/ticketek#8
